/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLGriddlerGamePlayStatus.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   griddler/v1
// Description:
//   Griddler API
// Classes:
//   GTLGriddlerGamePlayStatus (0 custom class methods, 2 custom properties)

#import "GTLGriddlerGamePlayStatus.h"

// ----------------------------------------------------------------------------
//
//   GTLGriddlerGamePlayStatus
//

@implementation GTLGriddlerGamePlayStatus
@dynamic correctAnswers, timeLeft;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[NSNumber class]
                                forKey:@"correctAnswers"];
  return map;
}

@end
