/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLGriddler_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   griddler/v1
// Description:
//   Griddler API

#import "GTLGriddlerConstants.m"

#import "GTLGriddlerBoard.m"
#import "GTLGriddlerGame.m"
#import "GTLGriddlerGamePlay.m"
#import "GTLGriddlerGamePlayStatus.m"
#import "GTLGriddlerInvitation.m"
#import "GTLGriddlerPlayer.m"
#import "GTLGriddlerPlayerCollection.m"
#import "GTLGriddlerPlayerStatistics.m"

#import "GTLQueryGriddler.m"
#import "GTLServiceGriddler.m"
