/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLGriddler.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   griddler/v1
// Description:
//   Griddler API

#import "GTLGriddlerConstants.h"

#import "GTLGriddlerBoard.h"
#import "GTLGriddlerGame.h"
#import "GTLGriddlerGamePlay.h"
#import "GTLGriddlerGamePlayStatus.h"
#import "GTLGriddlerInvitation.h"
#import "GTLGriddlerPlayer.h"
#import "GTLGriddlerPlayerCollection.h"
#import "GTLGriddlerPlayerStatistics.h"

#import "GTLQueryGriddler.h"
#import "GTLServiceGriddler.h"
