/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLGriddlerGamePlayStatus.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   griddler/v1
// Description:
//   Griddler API
// Classes:
//   GTLGriddlerGamePlayStatus (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLGriddlerGamePlayStatus
//

@interface GTLGriddlerGamePlayStatus : GTLObject
@property (retain) NSArray *correctAnswers;  // of NSNumber (intValue)
@property (retain) NSNumber *timeLeft;  // longLongValue
@end
