/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLGriddlerBoard.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   griddler/v1
// Description:
//   Griddler API
// Classes:
//   GTLGriddlerBoard (0 custom class methods, 4 custom properties)

#import "GTLGriddlerBoard.h"

// ----------------------------------------------------------------------------
//
//   GTLGriddlerBoard
//

@implementation GTLGriddlerBoard
@dynamic allottedTime, answers, gridDefinition, riddles;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      [NSString class], @"answers",
      [NSString class], @"gridDefinition",
      [NSString class], @"riddles",
      nil];
  return map;
}

@end
