/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLGriddlerBoard.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   griddler/v1
// Description:
//   Griddler API
// Classes:
//   GTLGriddlerBoard (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLGriddlerBoard
//

@interface GTLGriddlerBoard : GTLObject
@property (retain) NSNumber *allottedTime;  // longLongValue
@property (retain) NSArray *answers;  // of NSString
@property (retain) NSArray *gridDefinition;  // of NSString
@property (retain) NSArray *riddles;  // of NSString
@end
