/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLGriddlerGamePlay.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   griddler/v1
// Description:
//   Griddler API
// Classes:
//   GTLGriddlerGamePlay (0 custom class methods, 5 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLGriddlerPlayer;

// ----------------------------------------------------------------------------
//
//   GTLGriddlerGamePlay
//

@interface GTLGriddlerGamePlay : GTLObject
@property (retain) NSArray *correctAnswers;  // of NSNumber (intValue)
@property (retain) NSNumber *finished;  // boolValue
@property (retain) NSNumber *isWinner;  // boolValue
@property (retain) GTLGriddlerPlayer *player;
@property (retain) NSNumber *timeLeft;  // longLongValue
@end
