/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLGriddlerPlayerCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   griddler/v1
// Description:
//   Griddler API
// Classes:
//   GTLGriddlerPlayerCollection (0 custom class methods, 1 custom properties)

#import "GTLGriddlerPlayerCollection.h"

#import "GTLGriddlerPlayer.h"

// ----------------------------------------------------------------------------
//
//   GTLGriddlerPlayerCollection
//

@implementation GTLGriddlerPlayerCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLGriddlerPlayer class]
                                forKey:@"items"];
  return map;
}

@end
