/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLGriddlerInvitation.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   griddler/v1
// Description:
//   Griddler API
// Classes:
//   GTLGriddlerInvitation (0 custom class methods, 3 custom properties)

#import "GTLGriddlerInvitation.h"

// ----------------------------------------------------------------------------
//
//   GTLGriddlerInvitation
//

@implementation GTLGriddlerInvitation
@dynamic gameId, invitationId, status;
@end
