/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLGriddlerGame.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   griddler/v1
// Description:
//   Griddler API
// Classes:
//   GTLGriddlerGame (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLGriddlerBoard;
@class GTLGriddlerGamePlay;

// ----------------------------------------------------------------------------
//
//   GTLGriddlerGame
//

@interface GTLGriddlerGame : GTLObject
@property (retain) GTLGriddlerBoard *board;
@property (retain) NSArray *gamePlays;  // of GTLGriddlerGamePlay

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@end
