/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLGriddlerGame.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   griddler/v1
// Description:
//   Griddler API
// Classes:
//   GTLGriddlerGame (0 custom class methods, 3 custom properties)

#import "GTLGriddlerGame.h"

#import "GTLGriddlerBoard.h"
#import "GTLGriddlerGamePlay.h"

// ----------------------------------------------------------------------------
//
//   GTLGriddlerGame
//

@implementation GTLGriddlerGame
@dynamic board, gamePlays, identifier;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLGriddlerGamePlay class]
                                forKey:@"gamePlays"];
  return map;
}

@end
