/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLGriddlerGamePlay.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   griddler/v1
// Description:
//   Griddler API
// Classes:
//   GTLGriddlerGamePlay (0 custom class methods, 5 custom properties)

#import "GTLGriddlerGamePlay.h"

#import "GTLGriddlerPlayer.h"

// ----------------------------------------------------------------------------
//
//   GTLGriddlerGamePlay
//

@implementation GTLGriddlerGamePlay
@dynamic correctAnswers, finished, isWinner, player, timeLeft;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[NSNumber class]
                                forKey:@"correctAnswers"];
  return map;
}

@end
