/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLGriddlerConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   griddler/v1
// Description:
//   Griddler API

#import "GTLGriddlerConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeGriddlerUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
