/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLGriddlerPlayerStatistics.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   griddler/v1
// Description:
//   Griddler API
// Classes:
//   GTLGriddlerPlayerStatistics (0 custom class methods, 2 custom properties)

#import "GTLGriddlerPlayerStatistics.h"

// ----------------------------------------------------------------------------
//
//   GTLGriddlerPlayerStatistics
//

@implementation GTLGriddlerPlayerStatistics
@dynamic numberOfGames, numberOfWins;
@end
