/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLQueryGriddler.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   griddler/v1
// Description:
//   Griddler API
// Classes:
//   GTLQueryGriddler (15 custom class methods, 10 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLGriddlerGamePlayStatus;

@interface GTLQueryGriddler : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (assign) NSInteger boardLevel;
@property (copy) NSString *deviceId;
@property (assign) NSInteger deviceType;
@property (assign) long long gameId;
@property (copy) NSString *googlePlusId;
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (assign) long long identifier;
@property (assign) long long invitationId;
@property (copy) NSString *inviteeGooglePlusId;
@property (assign) long long inviteeId;

#pragma mark -
#pragma mark "gameEndpoint" methods
// These create a GTLQueryGriddler object.

// Method: griddler.gameEndpoint.acceptInvitation
//  Authorization scope(s):
//   kGTLAuthScopeGriddlerUserinfoEmail
+ (id)queryForGameEndpointAcceptInvitationWithGameId:(long long)gameId
                                        invitationId:(long long)invitationId;

// Method: griddler.gameEndpoint.cancelInvitation
//  Authorization scope(s):
//   kGTLAuthScopeGriddlerUserinfoEmail
+ (id)queryForGameEndpointCancelInvitationWithGameId:(long long)gameId
                                        invitationId:(long long)invitationId;

// Method: griddler.gameEndpoint.declineInvitation
//  Authorization scope(s):
//   kGTLAuthScopeGriddlerUserinfoEmail
+ (id)queryForGameEndpointDeclineInvitationWithGameId:(long long)gameId
                                         invitationId:(long long)invitationId;

// Method: griddler.gameEndpoint.getGame
//  Authorization scope(s):
//   kGTLAuthScopeGriddlerUserinfoEmail
// Fetches a GTLGriddlerGame.
+ (id)queryForGameEndpointGetGameWithIdentifier:(long long)identifier;

// Method: griddler.gameEndpoint.getInvitationStatus
//  Authorization scope(s):
//   kGTLAuthScopeGriddlerUserinfoEmail
// Fetches a GTLGriddlerInvitation.
+ (id)queryForGameEndpointGetInvitationStatusWithGameId:(long long)gameId
                                           invitationId:(long long)invitationId;

// Method: griddler.gameEndpoint.startMultiplayerGame
//  Authorization scope(s):
//   kGTLAuthScopeGriddlerUserinfoEmail
// Fetches a GTLGriddlerInvitation.
+ (id)queryForGameEndpointStartMultiplayerGameWithBoardLevel:(NSInteger)boardLevel
                                                   inviteeId:(long long)inviteeId;

// Method: griddler.gameEndpoint.startMultiplayerGameByGooglePlusId
//  Authorization scope(s):
//   kGTLAuthScopeGriddlerUserinfoEmail
// Fetches a GTLGriddlerInvitation.
+ (id)queryForGameEndpointStartMultiplayerGameByGooglePlusIdWithBoardLevel:(NSInteger)boardLevel
                                                       inviteeGooglePlusId:(NSString *)inviteeGooglePlusId;

// Method: griddler.gameEndpoint.startSinglePlayerGame
//  Authorization scope(s):
//   kGTLAuthScopeGriddlerUserinfoEmail
// Fetches a GTLGriddlerGame.
+ (id)queryForGameEndpointStartSinglePlayerGameWithBoardLevel:(NSInteger)boardLevel;

// Method: griddler.gameEndpoint.submitAnswers
//  Authorization scope(s):
//   kGTLAuthScopeGriddlerUserinfoEmail
+ (id)queryForGameEndpointSubmitAnswersWithObject:(GTLGriddlerGamePlayStatus *)object
                                       identifier:(long long)identifier;

#pragma mark -
#pragma mark "playerEndpoint" methods
// These create a GTLQueryGriddler object.

// Method: griddler.playerEndpoint.assignPlayerPlusId
//  Authorization scope(s):
//   kGTLAuthScopeGriddlerUserinfoEmail
+ (id)queryForPlayerEndpointAssignPlayerPlusIdWithGooglePlusId:(NSString *)googlePlusId;

// Method: griddler.playerEndpoint.get
//  Authorization scope(s):
//   kGTLAuthScopeGriddlerUserinfoEmail
// Fetches a GTLGriddlerPlayer.
+ (id)queryForPlayerEndpointGet;

// Method: griddler.playerEndpoint.insert
//  Authorization scope(s):
//   kGTLAuthScopeGriddlerUserinfoEmail
// Fetches a GTLGriddlerPlayer.
+ (id)queryForPlayerEndpointInsertWithGooglePlusId:(NSString *)googlePlusId;

// Method: griddler.playerEndpoint.list
//  Authorization scope(s):
//   kGTLAuthScopeGriddlerUserinfoEmail
// Fetches a GTLGriddlerPlayerCollection.
+ (id)queryForPlayerEndpointList;

// Method: griddler.playerEndpoint.registerDevice
//  Authorization scope(s):
//   kGTLAuthScopeGriddlerUserinfoEmail
+ (id)queryForPlayerEndpointRegisterDeviceWithDeviceId:(NSString *)deviceId
                                            deviceType:(NSInteger)deviceType;

// Method: griddler.playerEndpoint.unRegisterDevice
//  Authorization scope(s):
//   kGTLAuthScopeGriddlerUserinfoEmail
+ (id)queryForPlayerEndpointUnRegisterDeviceWithDeviceId:(NSString *)deviceId;

@end
